[env:esp32-c6]
; Bringt Arduino-ESP32 Core 3.x in PIO (wichtig für C6)
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
  madhephaestus/ESP32Servo

upload_port = COM6
monitor_port = COM6